### ISSUE TITLE
Rank mod doesn't work when players are offline

### ISSUE THREAD

**Issue by davisonio** [davisonio/craig-server_game#105]

**Comment by An0n3m0us** [comment]
Partial fix after merge of https://github.com/octacian/ranks/pull/3

**Comment by davisonio** [comment]
Great. Hopefully they merge soon. Or you could create a PR so we can add here sooner?

**Comment by An0n3m0us** [comment]
Okay, I'll try and do that tonight. I'll test it beforehand of course.

**Comment by davisonio** [comment]
Awesome!
