### ISSUE TITLE
shop error

### ISSUE THREAD

**Issue by RHRhino** [davisonio/craig-server_game#26]
When I placed a shop I got following message:
22:27:16: ERROR[main]: InventoryMenu: The selected inventory location "nodemeta: 66,3,37" doesn't exist
But I wasn't able to reproduce it. The second shop I placed had no problems ...

**Comment by CraigyDavi** [comment]
I think this is caused by placing a shop at an invalid location.
This code might fix it, but I haven't seen anyone else get this error:
```
if not name then
        return
end
```
