### ISSUE TITLE
torches + fences

### ISSUE THREAD

**Issue by RHRhino** [davisonio/craig-server_game#35]
Not sure if you can remember but before the server was down we talked about adding the torches from carbone (=nodeboxes) and about the change of the fence code so that fences connect like in the mod xfences (connections to all full blocks instead of just between fences)

https://github.com/Calinou/carbone/blob/master/mods/default/nodes.lua#L1103
https://forum.minetest.net/viewtopic.php?id=2127
https://github.com/xyzz/minetest-mods/tree/master/xfences

**Comment by CraigyDavi** [comment]
The torches can be added, I just need to check that there are no side-effects but the fences might take a little more work considering that we now have more fences from the fence mod - but it can still be done.

**Comment by CraigyDavi** [comment]
I'm closing this now:
- New torches (from Carbone) have just been added!
- `xfences` won't be added for the moment. The way it's implemented is very hacky and it's only designed for the wooden fence (rather than all the fences from the `fences` mod.)

**Comment by RHRhino** [comment]
Hey Craig I just found this. Is it more useful for fences?
https://forum.minetest.net/viewtopic.php?f=9&t=12882
https://github.com/Sokomine/xconnected

**Comment by CraigyDavi** [comment]
> Hey Craig I just found this. Is it more useful for fences?
> https://forum.minetest.net/viewtopic.php?f=9&t=12882
> https://github.com/Sokomine/xconnected

That mod looks great, I only need to add one line to add support for the fences :smile: 

I'll add this in a few days once I have time to test.

**Comment by RHRhino** [comment]
This can be closed, because both are now working! :smile:
