### ISSUE TITLE
Industry pack items produce unknown nodes

### ISSUE THREAD

**Issue by davisonio** [davisonio/craig-server_game#61]

**Comment by GaboXandre** [comment]
The unknown nodes are mainly rubber:rubber_tree_full, you can alias them to default:tree.

**Comment by davisonio** [comment]
> The unknown nodes are mainly rubber:rubber_tree_full, you can alias them to default:tree.

Thanks, have done in https://github.com/davisonio/craig-server_game/commit/4489923ef9c82fb81daf726469f910c4e69846a1 :smile:
