### ISSUE TITLE
I can't connect to the server, because my playername is not pronounceable 

### ISSUE THREAD

**Issue by RHRhino** [davisonio/craig-server_game#71]
@davisonio I hope you fix that soon! :sob:

**Comment by davisonio** [comment]
Sorry about this! The feature is very experimental so I've disabled it in https://github.com/davisonio/craig-server_game/commit/2f697255204afaf8586f8eae50d52bcc92b43340. You should be able to join right now!

I've made quite a few changes today so if you notice any more problems feel free to open an issue here. :)
