### ISSUE TITLE
Moreblocks microblocks should not show in the craft guide

### ISSUE THREAD

**Issue by davisonio** [davisonio/craig-server_game#72]

**Comment by lisacvuk** [comment]
Should they be? I mean, it's pretty easy to fix.

**Comment by davisonio** [comment]
Yep it's just these lines which need the `not_in_craft_guide=1` group added to them:
* https://github.com/davisonio/craig-server_game/blob/df013697b83e47f8db853fa795005399133d7a92/mods/moreblocks/nodes.lua#L335
* https://github.com/davisonio/craig-server_game/blob/1ad954e02f4b62bd4fcc69b977cba21ecee6e145/mods/moreblocks/stairsplus/registrations.lua#L58

**Comment by davisonio** [comment]
Fixed
