### ISSUE TITLE
Name restriction mod preventing some old players from joining.

### ISSUE THREAD

**Issue by fishyWET** [davisonio/craig-server_game#87]
A player joined by the name of "bigtrapaille0402" today.
He claimed that he wasn't able to access his old account, "Dim025", <bigtrapaille0402> "guest account as been disabled", seems like the name restriction mod is blocking more names than it should.

**Comment by fishyWET** [comment]
Another player was caught by the filter again. His nick was "Bishop1203"
The cause of this is due to @lisacvuk commit; https://github.com/davisonio/craig-server_game/commit/ba686bfb2c553ba8a5084e088238cd37442662bc

Can i propose to revert that commit?
I understand it is to detect guest accounts which uses the format, but there are many players who use this format for their names too, for example, a common usage is <nick><birthyear>, or <nick><number> just because the nick already exists.

**Comment by davisonio** [comment]
Sorted in https://github.com/davisonio/craig-server_game/commit/109e0d460418dd94026ac02d312e8f990ad7af80 thanks for reporting and sorry this took so long.

**Comment by lisacvuk** [comment]
@davisonio, the right solution was to use the whilelist and keep my commit, IMO. Like this we'll get flooded by guests again.
