### ISSUE TITLE
Suggestion: Events

### ISSUE THREAD

**Issue by neinwhal** [davisonio/craig-server_game#90]
Suggested this a while ago but there's no development that I know of.
Events could rejuvenate the server activity. Let's be frank, there is really nothing much to do once you build your house and mine up some ores.

Events could be in various forms. Building competitions, holiday events, PvE events, PvP events or various competitions.
But of course organizing an event is more complicated. So preferably someone active enough could handle this task.

**Comment by Amaz1** [comment]
Thanks for volunteering to handle them, neinwhal!

But yes, this does sound like a good idea.

**Comment by davisonio** [comment]
Yes this sounds like a great idea! The only thing we once did a while back was doing a halloween pumpkin hunt back in 2013/2014. If anyone's up for doing any new events let me know what you need to organise.

**Comment by neinwhal** [comment]
Some ideas;

**Competitions:**
- Build Competitions
  - Organized monthly
  - With a different theme each month
  - Builds have a set time and must be built in a fixed area, where after the competition finished, the entire building area can be transformed into a little tourism town
  - Winners get special tools, bitcoins or expensive resources

- PvP Competitions
  - Organized occassionally, events takes place within the time-span of a week or so.
  - Special hunger-games style arena
  - Join anytime but you can only leave after you die or you are the only one in the arena
  - Kill-counts are kept track of. When the event ends, players with highest kill-counts wins.

**Special Events**
- Halloween Events
  - As 2013/2014 could work
  - Or PvE with zombies or such, PvE kill-counts kept track of. Highest kill-count when event ends wins.
  - Could coincide with build competition OR build com could be end earlier and made use of to provide a nice halloween town for the actual event.

- Christmas Events
  - See above
  - Possible change in textures so everything appears snowy.

**Comment by davisonio** [comment]
Sounds good - just merged those two PR so consider this closed for now!
