### ISSUE TITLE
Suggestion: Interact mod

### ISSUE THREAD

**Issue by neinwhal** [davisonio/craig-server_game#91]
@Amaz1 has a mod that grants interact only after the player accepts a set of rules, and correctly answering a set of quizzes.
https://forum.minetest.net/viewtopic.php?t=11200

I have used this mod and seen this mod in practice and it really helps weeds out players who don't understand basic English. Especially if it is set to kick players after they fail to answer the basic quiz correctly.

This will be a really nice addition, considering the unsatisfactory players the server have been getting most of the time.

**Comment by davisonio** [comment]
Not going to add this for now - I want to make it as easy as possible for new players to get started (even if this means a slight increase in bad players). We can always ban these bad players.
