### ISSUE TITLE
Suggestion: Debug mod

### ISSUE THREAD

**Issue by neinwhal** [davisonio/craig-server_game#92]
lumber has created a mod that allows viewing of debug.txt remotely a while ago.
https://forum.minetest.net/viewtopic.php?t=18622

Rather than just using our eyes or just having to trust all victims. Access to debug.txt will be extremely useful when spotting things like unagreed PvP, stealing of items, griefing etc.

**Comment by davisonio** [comment]
I'll need to change the location of my logfiles for this to happen - so I can do that and this can be done!
