### ISSUE TITLE
Suggestion: Snow biomes

### ISSUE THREAD

**Issue by neinwhal** [davisonio/craig-server_game#93]
Snow biomes are just a setting ("mgv6_spflags = snowbiomes" in map_meta.txt) away from being generated.

So why not leave it enabled? It would create a really fantastic new environment to build in, opens up a whole new theme and blocks, also considering now that the new spawn has many unregenerated chunks.

Regarding sharp edges and cliffs, based on my results of a 0.4.13 world brought over, cliffs are mild at worst, especially considering the mild nature of v6, in fact they blend in quite well.
Sharp biome edges are unavoidable, but it was a rare encounter, most snow biomes generated further away, even if so, it really isnt that severe of an eye sore. But of course, this varies from different worlds.
Even if so, I'm sure there will be some players that will dedicate to terraforming/landscaping those ugly areas to fit in.

IMO, the benefits of the additional of the snow biome far counters the mild inconveniences of the cliffs and sharp edges, the snow biome adds a entire new environment, new theme, new blocks.

**Comment by davisonio** [comment]
Added! Even though lots of the world is generated this is cool to add.
