### ISSUE TITLE
Suggestion: Cleaner source of sand, dirt, gravel.

### ISSUE THREAD

**Issue by neinwhal** [davisonio/craig-server_game#97]
The current way sand, dirt and gravel are obtained really disfigure environment, especially more so that they are usually obtained in large amounts.

My suggestion is to allow them to be craftable from cobble.
Cobble > Gravel > Sand
Sand + Stone > Dirt
Desert Cobble > Desert Sand
Just so that there will be a way to get these materials without destroying desert, beaches, forests into ugly stone faces.

**Comment by davisonio** [comment]
I'm happy for this. Create a PR in the `craig_server` mod and I will merge.

**Comment by neinwhal** [comment]
Merged in #109
